accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:id>/mypage/', views.mypage, name='mypage'),
]

board/urls.py
from django.contrib import admin
from django.urls import path, include
from posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('', views.index)
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/', views.detail, name='detail'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/comment-create/', views.comment_create, name='comment_create'),
    path('<int:post_id>/comment-delete/<int:comment_id>', views.comment_delete, name='comment_delete'),
    path('search/', views.search, name='search'),
    path('<int:id>/like/', views.like, name='like'),
    path('<int:post_id>/like-comment/<int:comment_id>/', views.like_comment, name='like_comment'),
]

posts/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created_at = models.DateField(auto_now_add=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='like_comments')
    class Meta:
        ordering = ('-id',)

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from posts.models import Post, Comment


# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('posts:index')
    else:
        form = UserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'posts:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

def logout(request):
    auth_logout(request)
    return redirect('posts:index')

@login_required
def mypage(request, id):

    posts = Post.objects.filter(user_id=id)
    comments = Comment.objects.filter(user_id=id)
    context = {
        'posts': posts,
        'comments': comments
    }
    
    return render(request, 'accounts/mypage.html', context)

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.conf import settings

# Create your views here.

def index(request):
    posts = Post.objects.order_by('-id')
    # print(dir(settings.AUTH_USER_MODEL))
    context = {
        'posts': posts
    }
    return render(request, 'posts/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:index')
    else:
        form = PostForm()
    context = {
        'form': form
    }
    return render(request, 'posts/form.html', context)

@login_required
def detail(request, id):
    post = get_object_or_404(Post, id=id)
    comment_form = CommentForm()
    context = {
        'post': post,
        'comment_form': comment_form,
    }
    return render(request, 'posts/detail.html', context)

@login_required
def update(request, id):
    post = get_object_or_404(Post, id=id)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post.save()
            return redirect('posts:detail', id)

    else:
        form = PostForm(instance=post)
    context = {
        'form': form
    }
    return render(request, 'posts/form.html', context)

@login_required
@require_POST
def delete(request, id):
    post = get_object_or_404(Post, id=id)
    post.delete()
    return redirect('posts:index')

@require_POST
def comment_create(request, id):
    comment_form = CommentForm(request.POST)
    post = get_object_or_404(Post, id=id)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.post = post
        comment.save()
        return redirect('posts:detail', id)

@login_required
def comment_delete(request, post_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return redirect('posts:detail', post_id)


def search(request):
    keyword = request.GET.get('keyword')
    # 제목
    posts = Post.objects.filter(title__icontains=keyword)

    context = {
        'posts': posts
    }
    return render(request, 'posts/index.html', context)

@login_required
def like(request, id):
    post = get_object_or_404(Post, id=id)
    user = request.user
    if user in post.like_users.all():
        post.like_users.remove(user)
    else:
        post.like_users.add(user)
    return redirect('posts:detail', id)

@login_required
def like_comment(request, comment_id, post_id):
    comment = get_object_or_404(Comment, id=comment_id)
    user = request.user
    
    if comment.like_users.filter(id=user.id):
    # if user in comment.like_users.all():
        comment.like_users.remove(user)
    else:
        comment.like_users.add(user)
    return redirect('posts:detail', post_id)

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit">
    </form>
{% endblock %}

accounts/templates/accounts/mypage.html
{% extends 'base.html' %}

{% block body %}

<h3 class=>My Page</h3>
<h4>게시물</h4>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col" class="text-center">Write by</th>
        <th scope="col" class="text-center">Created at</th>
      </tr>
    </thead>
    <tbody>
      {% for post in posts %}
        <tr>
          <th scope="row">{{post.id}}</th>
          <td>
            <a href="{% url 'posts:detail' post.id %}">
              {{post.title}}
            </a>
          </td>
          <td class="text-center">{{post.user.username}}</td>
          <td class="text-center">{{post.created_at}}</td>
        </tr>
      {% empty %}
        <h4> 작성한 게시물이 없습니다. </h4>
      {% endfor %}
    </tbody>
  </table>

<h4>댓글</h4>
<table class="table table-sm">
    <thead> 
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Commnet</th>
      </tr>
    </thead>
    <tbody>
        
      {% for comment in comments %}
        <tr>
          <td scope="row">{{comment.user}}</td>
          <td>
            {{comment.content}} 
          </td>
        </tr>
      {% empty %}
        <tr class="text-center">
          <td scope="row" colspan="2">등록한 댓글이 없습니다.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

board/templates/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Do+Hyeon|Jua|Nanum+Gothic+Coding&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/e87731a046.js" crossorigin="anonymous"></script>
    <title>Document</title>
    <style>
        .jua {
            font-family: 'Jua', sans-serif;
        }
        .do {
            font-family: 'Do Hyeon', sans-serif;
        }    
        .go {
            font-family: 'Nanum Gothic Coding', monospace;
        }
        a:link {text-decoration: none; color: #17a2b8;}
        a:visited {text-decoration: none; color: #17a2b8;}

        body {
            background-image: url("{% static 'bono.gif' %}");
        }
    </style>
    {% bootstrap_css %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand ml-5 do" href="{% url 'posts:index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-item nav-link text-info" href="{% url 'accounts:mypage' user.id %}">{{user.username}}님</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link text-light" href="{% url 'posts:create' %}">새 글 작성</a>
                    </li>   
                    <li class="nav-item">
                        <a class="nav-item nav-link text-light" href="{% url 'accounts:logout' %}">로그아웃</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-item nav-link active" href="{% url 'accounts:signup' %}">가입하기<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-item nav-link" href="{% url 'accounts:login' %}">로그인</a>
                    </li>
                {% endif %}
            </ul>
            <form class="form-inline my-2 my-lg-0 mr-5" action="{% url 'posts:search' %}">
                <input class="form-control mr-sm-2" type="search" placeholder="제목검색" aria-label="Search" name="keyword">
                <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
            </form> 
        </div>
    </nav>

    <div class="container mt-5">
        {% block body %}
        {% endblock %}
    </div>
    {% bootstrap_javascript jquery='full' %}
</body>
</html>

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
  <div class="jumbotron">
    <div class="d-flex flex-row-reverse">
      <form action="{% url 'posts:delete' post.id %}" method="post" class="d-inline">
        {% csrf_token %}
        <button type="submit" class="btn"><i class="far fa-trash-alt text-danger"></i></button>
      </form>
      <form action="{% url 'posts:update' post.id %}" class="d-inline ">
        <button type="submit" class="btn"><i class="fas fa-edit text-info"></i></button>
      </form>
    </div>
    <h1 class="display-4">{{post.title}}</h1>
    <p>{{post.user.username}} | {{post.created_at}}</p>

    <hr>
    <p class="lead">{{post.content}}</p>
    {% if user in post.like_users.all %}
      <a href="{% url 'posts:like' post.id %}">취소요!</a>
    {% else %}
      <a href="{% url 'posts:like' post.id %}">좋아용</a>
    {% endif %}
  </div>

  <hr class="bg-info">

  <form action="{% url 'posts:comment_create' post.id %}" method="POST" class="my-5">
    {% csrf_token %}
    <div class="row">
      <div class="col-11 text-right">
        {% bootstrap_form comment_form layout="horizontal" size="small" label_class="form-label col-md-1" field_class="form-field col-md-11"%}
      </div>
      <div class="col-1 text-left">
        <input type="submit" class="btn btn-outline-info btn-sm">
      </div>
    </div>
  </form>
  
  
  
  <h5>전체 댓글</h5>
  <table class="table table-sm">
      <thead> 
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Commnet</th>
        </tr>
      </thead>
      <tbody>
        {% for comment in post.comment_set.all %}
          <tr>
            <td scope="row">{{comment.user.username}}</td>
            <td>
              {{comment.content}} [{{comment.like_users.all.count}}]
              <div>
                {% if user in comment.like_users.all %}
                  <a href="{% url 'posts:like_comment' post.id comment.id %}">취소요!</a>
                {% else %}
                  <a href="{% url 'posts:like_comment' post.id comment.id %}">좋아용</a>
                {% endif %}
              
              </div>
              {% if comment.user == user %}
              <div class='text-right'>
                <a href="{% url 'posts:comment_delete' post.id comment.id %}">
                  <i class="fas fa-backspace text-dark"></i>
                </a> 
              </div>
              {% endif %}
            </td>
          </tr>
        {% empty %}
          <tr class="text-center">
            <td scope="row" colspan="2">댓글을 등록해주세요.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
 


{% endblock %}

posts/templates/posts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="text-right">
      <input class="btn btn-info" type="submit">
    </div>
  </form>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}



  <hr>
  <hr>

  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col" class="text-center">Write by</th>
        <th scope="col" class="text-center">Likes</th>
        <th scope="col" class="text-center">Created at</th>
      </tr>
    </thead>
    <tbody>
      {% for post in posts %}
        <tr>
          <th scope="row">{{post.id}}</th>
          <td>
            <a href="{% url 'posts:detail' post.id %}">
              {{post.title}}
            </a>
          </td>
          <td class="text-center">{{post.user.username}}</td>
          <td class="text-center">{{post.like_users.all.count}}</td>
          <td class="text-center">{{post.created_at}}</td>
        </tr>
      {% empty %}
        <h4> 등록/검색된 게시물이 없습니다. </h4>
      {% endfor %}
    </tbody>
  </table>




{% endblock %}